### ISSUE TITLE
Using node built js causes $.widget is not a function error

### ISSUE THREAD

**Issue by instification** [collective/collective.tocify#5]
Steps to reproduce:

In the root of the package run:
`make bundle-tocify`

Update `index.html` to point the js and css to `./build/tocify.js` and `./build.tocify.min.css`

When loading the test page the following error is returned:

`Uncaught TypeError: $.widget is not a function`

**Comment by instification** [comment]
More info here
http://patternslib.com/load-custom-pattern-with-requirejs

**Comment by allcaps** [comment]
This has to do with the version of jQuery.ui and it's version. Fixed this in a newly created pattern. See:
- https://github.com/collective/pat-tocify/blob/master/bower.json#L8
- https://github.com/collective/pat-tocify/blob/master/main.js#L8
- https://github.com/collective/pat-tocify/blob/master/src/pat-tocify.js#L60
